name: AIAppLab_External
version: 1.4.2
summary: AI Application Lab environment (external configuration)
description: Deploy azure container apps and backend services like openai, cosmos, storage, etc...
runner: ARM
templatePath: main.bicep
parameters:
- id: "region"
  name: "region"
  description: "region name for main target"
  type: "string"
  required: true
- id: "aoaiRegion"
  name: "aoaiRegion"
  description: "region name for azure openai account"
  type: "string"
  required: true
- id: "allowedClientIp"
  name: "allowedClientIp"
  description: "public ip address of developer's outbound"
  type: "string"
  required: true
